receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # otlp:
  #   endpoint: otelcol:4317
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
      insecure_skip_verify: true
    #   cert_file: cert.pem
    #   key_file: cert-key.pem

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp]