version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./configuration/otel-collector-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - bookstore-network
    depends_on:
      - jaeger-all-in-one
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: bookstore_jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - bookstore-network
  prometheus:
    image: prom/prometheus
    container_name: bookstore_prometheus
    volumes:
      - ./configuration/prometheus-config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - bookstore-network
  grafana:
    image: grafana/grafana
    container_name: bookstore_grafana
    ports:
      - 3000:3000
    networks:
      - bookstore-network
  bookinfoapi:
    build: ./info/.
    container_name: bookinfoAPI
    ports:
      - "5550:5550"
    environment: 
      BASE_URL : ":5550"
      OTLP_ENDPOINT: "otel-collector:4317"
      ConnectionString: "mongodb://{username}:{password}@bookinfomongo:27017"
      DatabaseName: bookinfo
      DbUserName: mongoadmin
      DbPassword: secret
    networks:
      - bookstore-network
    depends_on:
      - bookinfomongo
      - otel-collector
  bookinfomongo:
    build: ./info/db/.
    container_name: bookinfo-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: bookinfo
    volumes: 
      - bookinfo-mongodata:/data/db
    networks:
      - bookstore-network
  bookstockapi:
    build: ./stock/.
    container_name: bookstockAPI
    ports:
      - "5551:5551"
    environment: 
      BASE_URL : ":5551"
      OTLP_ENDPOINT: "otel-collector:4317"
      ConnectionString: "bookstockredis:6379"
    networks:
      - bookstore-network
    depends_on:
      - bookstockredis
      - otel-collector
  bookstockredis:
    build: ./stock/db/.
    container_name: bookstock-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - bookstore-network      
networks:
  bookstore-network:    
volumes:
  bookinfo-mongodata:

