version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel-collector-config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    networks:
      - bookstore-network
    depends_on:
      - jaeger-all-in-one
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: bookstore_jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - bookstore-network      
  bookinfoapi:
    build: ./info/.
    container_name: bookinfoAPI
    ports:
      - "5550:5550"
    environment: 
      BASE_URL : ":5550"
      JAEGER_AGENT_HOST : "jaeger"
      JAEGER_AGENT_PORT : 6831
      ConnectionString: "mongodb://{username}:{password}@bookinfomongo:27017"
      DatabaseName: bookinfo
      DbUserName: mongoadmin
      DbPassword: secret
    networks:
      - bookstore-network
    depends_on:
      - bookinfomongo
      - otel-collector
  bookinfomongo:
    build: ./info/db/.
    container_name: bookinfo-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: bookinfo
    volumes: 
      - bookinfo-mongodata:/data/db
    networks:
      - bookstore-network
networks:
  bookstore-network:    
volumes:
  bookinfo-mongodata:

